name: Release

on:
  push:
    branches:
      - master
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  macos:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2
      - name: Install targets
        run: rustup update && rustup target add x86_64-apple-darwin aarch64-apple-darwin
      - name: Test
        run: cargo test --release
      - name: Make App
        run: make dmg-universal
      - uses: actions/upload-artifact@v2
        with:
          name: Universal DMG
          path: target/release/osx/Alacritty.dmg
